'use client';

import { useState } from 'react';
import { Search, FileDown, Eye, X, Check, Ban } from 'lucide-react';

interface POItem {
  name: string;
  qty: number;
  price: number;
}

interface PurchaseOrder {
  id: string;
  poNumber: string;
  vendor: string;
  vendorGst: string;
  vendorAddress: string;
  total: string;
  issuedDate: string;
  status: string;
  items: POItem[];
}

export default function PurchaseOrdersPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedPo, setSelectedPo] = useState<PurchaseOrder | null>(null);

  // PO List State
  const [ordersList, setOrdersList] = useState<PurchaseOrder[]>([
    { 
      id: '1', 
      poNumber: 'PO-2026-000101', 
      vendor: 'Supernova Logistics & Trading', 
      vendorGst: '27AAASL5678B1Z2',
      vendorAddress: 'Building 4B, Sector 3, Vashi, Navi Mumbai, MH, 400703',
      total: '12,42,540', 
      issuedDate: '2026-06-01', 
      status: 'ISSUED',
      items: [
        { name: 'Enterprise Server Rack 2U (Dual Xeon 32-Core, 256GB RAM, 8TB SSD)', qty: 3, price: 350000 }
      ]
    },
    { 
      id: '2', 
      poNumber: 'PO-2026-000102', 
      vendor: 'Apex Industrial Supplies', 
      vendorGst: '27AAAAP9999C1Z3',
      vendorAddress: 'Phase 2, Industrial Area, Hinjewadi, Pune, MH, 411057',
      total: '2,60,544', 
      issuedDate: '2026-06-03', 
      status: 'ACKNOWLEDGED',
      items: [
        { name: 'Managed L3 Network Switch 48-Port PoE+ (10G SFP+ Uplinks)', qty: 2, price: 110400 }
      ]
    },
    { 
      id: '3', 
      poNumber: 'PO-2026-000103', 
      vendor: 'Zenith Tech Systems', 
      vendorGst: '27AAAZT8888D1Z4',
      vendorAddress: 'Tower C, DLF Cyber City, Phase 3, Gurugram, HR, 122002',
      total: '6,37,200', 
      issuedDate: '2026-05-28', 
      status: 'FULLY_RECEIVED',
      items: [
        { name: 'Standard Office Workstation Desks', qty: 10, price: 54000 }
      ]
    },
    { 
      id: '4', 
      poNumber: 'PO-2026-000104', 
      vendor: 'Titanium Steel Corp', 
      vendorGst: '27AAATC2222F1Z6',
      vendorAddress: 'Steel Yard Compound, Kalamboli, Navi Mumbai, MH, 410218',
      total: '16,75,600', 
      issuedDate: '2026-06-05', 
      status: 'ISSUED',
      items: [
        { name: 'Titanium Coated Steel Coils (Grade-A)', qty: 50, price: 28400 }
      ]
    },
  ]);

  // Download PO handler
  const handleDownloadPo = (po: PurchaseOrder) => {
    const header = `==================================================\n`;
    const title = `             PURCHASE ORDER: ${po.poNumber}\n`;
    const details = `Issued Date: ${po.issuedDate}\nStatus: ${po.status}\n\n`;
    const buyer = `Buyer Details:\nAcme Global Corporation\n101, BKC, Mumbai\nGSTIN: 27AAACA1234A1Z1\n\n`;
    const vendor = `Vendor Details:\n${po.vendor}\n${po.vendorAddress}\nGSTIN: ${po.vendorGst}\n\n`;
    
    let itemsTable = `Items Table:\n`;
    po.items.forEach(item => {
      itemsTable += `- ${item.name} | Qty: ${item.qty} | Price: INR ${item.price.toLocaleString()} | Total: INR ${(item.qty * item.price).toLocaleString()}\n`;
    });
    
    const footer = `\nTotal Value: INR ${po.total}\n==================================================\nGenerated by VendorBridge ERP Platform.\n`;
    
    const content = `${header}${title}${header}${details}${buyer}${vendor}${itemsTable}${footer}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${po.poNumber}_Details.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // State modification handlers
  const handleApprovePo = (id: string) => {
    setOrdersList(ordersList.map(o => o.id === id ? { ...o, status: 'ACKNOWLEDGED' } : o));
    if (selectedPo && selectedPo.id === id) {
      setSelectedPo({ ...selectedPo, status: 'ACKNOWLEDGED' });
    }
  };

  const handleCancelPo = (id: string) => {
    setOrdersList(ordersList.map(o => o.id === id ? { ...o, status: 'CANCELLED' } : o));
    if (selectedPo && selectedPo.id === id) {
      setSelectedPo({ ...selectedPo, status: 'CANCELLED' });
    }
  };

  const filteredOrders = ordersList.filter(o => 
    o.poNumber.includes(searchTerm) || o.vendor.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Purchase Orders</h1>
          <p className="text-sm text-slate-500 mt-1">Review, print, and track corporate purchase commitments.</p>
        </div>
      </div>

      <div className="flex bg-white p-4 rounded-xl border border-slate-200/80 shadow-sm shadow-slate-100/50 justify-between">
        <div className="relative w-full sm:w-80">
          <span className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none text-slate-400">
            <Search className="w-4 h-4" />
          </span>
          <input
            type="text"
            placeholder="Search PO number or vendor..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm text-slate-700 placeholder-slate-400 focus:outline-none focus:border-accent focus:bg-white transition-colors"
          />
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200/80 shadow-sm shadow-slate-100/50 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-semibold text-xs uppercase tracking-wider">
                <th className="px-6 py-4">PO Number</th>
                <th className="px-6 py-4">Vendor</th>
                <th className="px-6 py-4">Issued Date</th>
                <th className="px-6 py-4">Amount</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-sm text-slate-600">
              {filteredOrders.map((order) => (
                <tr key={order.id} className="hover:bg-slate-50/50 transition-colors">
                  <td className="px-6 py-4 font-semibold text-slate-800">{order.poNumber}</td>
                  <td className="px-6 py-4">{order.vendor}</td>
                  <td className="px-6 py-4">{order.issuedDate}</td>
                  <td className="px-6 py-4 font-semibold text-slate-700">₹{order.total}</td>
                  <td className="px-6 py-4">
                    <span
                      className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold ${
                        order.status === 'ISSUED'
                          ? 'bg-blue-50 text-blue-700'
                          : order.status === 'ACKNOWLEDGED'
                          ? 'bg-amber-50 text-amber-700'
                          : order.status === 'CANCELLED'
                          ? 'bg-slate-100 text-slate-600'
                          : 'bg-emerald-50 text-emerald-700'
                      }`}
                    >
                      {order.status.replace('_', ' ')}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      <button
                        onClick={() => setSelectedPo(order)}
                        className="p-1.5 text-slate-400 hover:text-accent rounded-lg hover:bg-slate-100 transition-all cursor-pointer flex items-center justify-center"
                        title="View PO Details"
                      >
                        <Eye className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleDownloadPo(order)}
                        className="p-1.5 text-slate-400 hover:text-slate-750 rounded-lg hover:bg-slate-100 transition-all cursor-pointer flex items-center justify-center"
                        title="Download PO Details"
                      >
                        <FileDown className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
              {filteredOrders.length === 0 && (
                <tr>
                  <td colSpan={6} className="text-center py-12 text-slate-400">
                    No purchase orders found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* PO Details Modal */}
      {selectedPo && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4 transition-all duration-300">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-2xl w-full flex flex-col">
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-slate-50">
              <div className="flex items-center gap-2">
                <span className="text-sm font-bold text-slate-800">{selectedPo.poNumber}</span>
                <span
                  className={`ml-2 inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold ${
                    selectedPo.status === 'ISSUED'
                      ? 'bg-blue-50 text-blue-700'
                      : selectedPo.status === 'ACKNOWLEDGED'
                      ? 'bg-amber-50 text-amber-700'
                      : selectedPo.status === 'CANCELLED'
                      ? 'bg-slate-100 text-slate-600'
                      : 'bg-emerald-50 text-emerald-700'
                  }`}
                >
                  {selectedPo.status.replace('_', ' ')}
                </span>
              </div>
              <button
                onClick={() => setSelectedPo(null)}
                className="p-1.5 hover:bg-slate-200 rounded-lg text-slate-400 hover:text-slate-650 transition-all cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-6 space-y-6 text-xs text-slate-650">
              <div className="grid grid-cols-2 gap-6 pb-4 border-b border-slate-100">
                <div>
                  <h3 className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Buyer (Bill To):</h3>
                  <div className="mt-1 space-y-0.5 text-slate-600">
                    <p className="font-semibold text-slate-800">Acme Global Corporation</p>
                    <p>101, BKC, Mumbai, Maharashtra, 400051</p>
                    <p className="font-medium text-slate-700">GSTIN: 27AAACA1234A1Z1</p>
                  </div>
                </div>
                <div>
                  <h3 className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Seller (Vendor):</h3>
                  <div className="mt-1 space-y-0.5 text-slate-600">
                    <p className="font-semibold text-slate-800">{selectedPo.vendor}</p>
                    <p>{selectedPo.vendorAddress}</p>
                    <p className="font-medium text-slate-700">GSTIN: {selectedPo.vendorGst}</p>
                  </div>
                </div>
              </div>

              {/* Items List */}
              <div className="space-y-2">
                <h3 className="font-bold text-slate-700 uppercase tracking-wider text-[10px]">Ordered items</h3>
                <div className="border border-slate-200 rounded-xl overflow-hidden">
                  <table className="w-full text-left border-collapse text-xs">
                    <thead>
                      <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold">
                        <th className="px-4 py-2.5">Description</th>
                        <th className="px-4 py-2.5 text-center w-20">Qty</th>
                        <th className="px-4 py-2.5 text-right w-28">Unit Price</th>
                        <th className="px-4 py-2.5 text-right w-28">Total</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 text-slate-600">
                      {selectedPo.items.map((item, idx) => (
                        <tr key={idx}>
                          <td className="px-4 py-2.5 font-medium text-slate-800">{item.name}</td>
                          <td className="px-4 py-2.5 text-center">{item.qty}</td>
                          <td className="px-4 py-2.5 text-right">₹{item.price.toLocaleString()}</td>
                          <td className="px-4 py-2.5 text-right font-semibold">₹{(item.qty * item.price).toLocaleString()}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              <div className="border-t border-slate-100 pt-4 flex items-center justify-between">
                <div>
                  <p className="text-[10px] text-slate-400">Total Purchase Commitment</p>
                  <p className="text-base font-bold text-slate-800 mt-0.5">₹{selectedPo.total}</p>
                </div>
                <div className="flex gap-1.5">
                  {selectedPo.status === 'ISSUED' && (
                    <>
                      <button
                        onClick={() => handleApprovePo(selectedPo.id)}
                        className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-lg shadow-sm cursor-pointer transition-colors"
                      >
                        <Check className="w-3.5 h-3.5" />
                        Acknowledge PO
                      </button>
                      <button
                        onClick={() => handleCancelPo(selectedPo.id)}
                        className="flex items-center gap-1.5 px-3 py-1.5 bg-rose-600 hover:bg-rose-500 text-white font-bold rounded-lg shadow-sm cursor-pointer transition-colors"
                      >
                        <Ban className="w-3.5 h-3.5" />
                        Cancel PO
                      </button>
                    </>
                  )}
                  <button
                    onClick={() => handleDownloadPo(selectedPo)}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-200 font-bold rounded-lg shadow-sm cursor-pointer transition-colors"
                  >
                    <FileDown className="w-3.5 h-3.5" />
                    Download Details
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
