'use client';

import { useState } from 'react';
import { Search, FileDown, Eye, X, Check, Ban } from 'lucide-react';
import { acknowledgePO, cancelPO } from '@/app/actions/purchase-orders';
import { useRouter } from 'next/navigation';

interface POItem {
  id: string;
  itemName: string;
  quantity: number;
  unitPrice: string;
  taxRate: string;
  totalAmount: string;
}

interface DbPurchaseOrder {
  id: string;
  poNumber: string;
  status: 'DRAFT' | 'ISSUED' | 'ACKNOWLEDGED' | 'PARTIALLY_RECEIVED' | 'FULLY_RECEIVED' | 'CLOSED' | 'CANCELLED';
  deliveryAddress: string;
  paymentTerms: string;
  issuedAt: Date | null;
  vendorName: string;
  vendorGst: string;
  vendorId: string;
  bankDetails: any;
  items: POItem[];
  total: string;
}

interface PurchaseOrdersClientProps {
  orders: DbPurchaseOrder[];
  userRole: string;
}

export default function PurchaseOrdersClient({ orders, userRole }: PurchaseOrdersClientProps) {
  const router = useRouter();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedPo, setSelectedPo] = useState<DbPurchaseOrder | null>(null);
  const [submitting, setSubmitting] = useState<Record<string, boolean>>({});

  const handleDownloadPo = (po: DbPurchaseOrder) => {
    const header = `==================================================\n`;
    const title = `             PURCHASE ORDER: ${po.poNumber}\n`;
    const details = `Issued Date: ${po.issuedAt ? new Date(po.issuedAt).toLocaleDateString('en-IN') : 'N/A'}\nStatus: ${po.status}\n\n`;
    const buyer = `Buyer Details:\nAcme Global Corporation\n101, BKC, Mumbai\nGSTIN: 27AAACA1234A1Z1\n\n`;
    const vendorAddress = po.bankDetails?.address || 'Registered Address';
    const vendor = `Vendor Details:\n${po.vendorName}\n${vendorAddress}\nGSTIN: ${po.vendorGst}\n\n`;
    
    let itemsTable = `Items Table:\n`;
    po.items.forEach(item => {
      itemsTable += `- ${item.itemName} | Qty: ${item.quantity} | Price: INR ${Number(item.unitPrice).toLocaleString()} | Tax: ${item.taxRate}% | Total: INR ${Number(item.totalAmount).toLocaleString()}\n`;
    });
    
    const footer = `\nTotal Value: INR ${po.total}\n==================================================\nGenerated by VendorBridge ERP Platform.\n`;
    
    const content = `${header}${title}${header}${details}${buyer}${vendor}${itemsTable}${footer}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${po.poNumber}_Details.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleApprovePo = async (id: string) => {
    setSubmitting(prev => ({ ...prev, [id]: true }));
    const res = await acknowledgePO(id);
    setSubmitting(prev => ({ ...prev, [id]: false }));

    if (res.success) {
      if (selectedPo && selectedPo.id === id) {
        setSelectedPo({ ...selectedPo, status: 'ACKNOWLEDGED' });
      }
      router.refresh();
    } else {
      alert(res.error || 'Failed to acknowledge purchase order');
    }
  };

  const handleCancelPo = async (id: string) => {
    setSubmitting(prev => ({ ...prev, [id]: true }));
    const res = await cancelPO(id);
    setSubmitting(prev => ({ ...prev, [id]: false }));

    if (res.success) {
      if (selectedPo && selectedPo.id === id) {
        setSelectedPo({ ...selectedPo, status: 'CANCELLED' });
      }
      router.refresh();
    } else {
      alert(res.error || 'Failed to cancel purchase order');
    }
  };

  const filteredOrders = orders.filter(o => 
    o.poNumber.includes(searchTerm) || o.vendorName.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Purchase Orders</h1>
          <p className="text-sm text-slate-500 mt-1">Review, print, and track corporate purchase commitments.</p>
        </div>
      </div>

      <div className="flex bg-white p-4 rounded-xl border border-slate-200/80 shadow-sm shadow-slate-100/50 justify-between">
        <div className="relative w-full sm:w-80">
          <span className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none text-slate-400">
            <Search className="w-4 h-4" />
          </span>
          <input
            type="text"
            placeholder="Search PO number or vendor..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm text-slate-700 placeholder-slate-400 focus:outline-none focus:border-accent focus:bg-white transition-colors"
          />
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200/80 shadow-sm shadow-slate-100/50 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-semibold text-xs uppercase tracking-wider">
                <th className="px-6 py-4">PO Number</th>
                <th className="px-6 py-4">Vendor</th>
                <th className="px-6 py-4">Issued Date</th>
                <th className="px-6 py-4">Amount</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-sm text-slate-600">
              {filteredOrders.map((order) => {
                const formattedDate = order.issuedAt 
                  ? new Date(order.issuedAt).toLocaleDateString('en-IN') 
                  : 'N/A';

                return (
                  <tr key={order.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-6 py-4 font-semibold text-slate-800">{order.poNumber}</td>
                    <td className="px-6 py-4">{order.vendorName}</td>
                    <td className="px-6 py-4">{formattedDate}</td>
                    <td className="px-6 py-4 font-semibold text-slate-700">₹{order.total}</td>
                    <td className="px-6 py-4">
                      <span
                        className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold ${
                          order.status === 'ISSUED'
                            ? 'bg-blue-50 text-blue-700'
                            : order.status === 'ACKNOWLEDGED'
                            ? 'bg-amber-50 text-amber-700'
                            : order.status === 'CANCELLED'
                            ? 'bg-slate-100 text-slate-600'
                            : 'bg-emerald-50 text-emerald-700'
                        }`}
                      >
                        {order.status.replace('_', ' ')}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex items-center justify-end gap-1.5">
                        <button
                          type="button"
                          onClick={() => setSelectedPo(order)}
                          className="p-2.5 text-slate-400 hover:text-accent rounded-lg hover:bg-slate-100 transition-all cursor-pointer flex items-center justify-center"
                          title="View PO Details"
                        >
                          <Eye className="w-5 h-5" />
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDownloadPo(order)}
                          className="p-2.5 text-slate-400 hover:text-slate-750 rounded-lg hover:bg-slate-100 transition-all cursor-pointer flex items-center justify-center"
                          title="Download PO Details"
                        >
                          <FileDown className="w-5 h-5" />
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
              {filteredOrders.length === 0 && (
                <tr>
                  <td colSpan={6} className="text-center py-12 text-slate-400">
                    No purchase orders found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* PO Details Modal */}
      {selectedPo && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4 transition-all duration-300">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-2xl w-full flex flex-col">
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-slate-50">
              <div className="flex items-center gap-2">
                <span className="text-sm font-bold text-slate-800">{selectedPo.poNumber}</span>
                <span
                  className={`ml-2 inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold ${
                    selectedPo.status === 'ISSUED'
                      ? 'bg-blue-50 text-blue-700'
                      : selectedPo.status === 'ACKNOWLEDGED'
                      ? 'bg-amber-50 text-amber-700'
                      : selectedPo.status === 'CANCELLED'
                      ? 'bg-slate-100 text-slate-600'
                      : 'bg-emerald-50 text-emerald-700'
                  }`}
                >
                  {selectedPo.status.replace('_', ' ')}
                </span>
              </div>
              <button
                onClick={() => setSelectedPo(null)}
                className="p-1.5 hover:bg-slate-200 rounded-lg text-slate-400 hover:text-slate-650 transition-all cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-6 space-y-6 text-xs text-slate-650">
              <div className="grid grid-cols-2 gap-6 pb-4 border-b border-slate-100">
                <div>
                  <h3 className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Buyer (Bill To):</h3>
                  <div className="mt-1 space-y-0.5 text-slate-600">
                    <p className="font-semibold text-slate-800">Acme Global Corporation</p>
                    <p>101, BKC, Mumbai, Maharashtra, 400051</p>
                    <p className="font-medium text-slate-700">GSTIN: 27AAACA1234A1Z1</p>
                  </div>
                </div>
                <div>
                  <h3 className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Seller (Vendor):</h3>
                  <div className="mt-1 space-y-0.5 text-slate-600">
                    <p className="font-semibold text-slate-800">{selectedPo.vendorName}</p>
                    <p>{selectedPo.bankDetails?.address || 'Registered Address'}</p>
                    <p className="font-medium text-slate-700">GSTIN: {selectedPo.vendorGst}</p>
                  </div>
                </div>
              </div>

              {/* Items List */}
              <div className="space-y-2">
                <h3 className="font-bold text-slate-700 uppercase tracking-wider text-[10px]">Ordered items</h3>
                <div className="border border-slate-200 rounded-xl overflow-hidden">
                  <table className="w-full text-left border-collapse text-xs">
                    <thead>
                      <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold">
                        <th className="px-4 py-2.5">Description</th>
                        <th className="px-4 py-2.5 text-center w-20">Qty</th>
                        <th className="px-4 py-2.5 text-right w-28">Unit Price</th>
                        <th className="px-4 py-2.5 text-right w-28">Total</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 text-slate-600">
                      {selectedPo.items.map((item, idx) => (
                        <tr key={idx}>
                          <td className="px-4 py-2.5 font-medium text-slate-800">{item.itemName}</td>
                          <td className="px-4 py-2.5 text-center">{item.quantity}</td>
                          <td className="px-4 py-2.5 text-right">₹{Number(item.unitPrice).toLocaleString()}</td>
                          <td className="px-4 py-2.5 text-right font-semibold">₹{Number(item.totalAmount).toLocaleString()}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              <div className="border-t border-slate-100 pt-4 flex items-center justify-between">
                <div>
                  <p className="text-[10px] text-slate-400">Total Purchase Commitment</p>
                  <p className="text-base font-bold text-slate-800 mt-0.5">₹{selectedPo.total}</p>
                </div>
                <div className="flex gap-1.5">
                  {selectedPo.status === 'ISSUED' && (
                    <>
                      {userRole === 'VENDOR' ? (
                        <button
                          disabled={submitting[selectedPo.id]}
                          onClick={() => handleApprovePo(selectedPo.id)}
                          className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-lg shadow-sm cursor-pointer transition-colors disabled:opacity-50"
                        >
                          <Check className="w-3.5 h-3.5" />
                          Acknowledge PO
                        </button>
                      ) : (
                        <button
                          disabled={submitting[selectedPo.id]}
                          onClick={() => handleCancelPo(selectedPo.id)}
                          className="flex items-center gap-1.5 px-3 py-1.5 bg-rose-600 hover:bg-rose-500 text-white font-bold rounded-lg shadow-sm cursor-pointer transition-colors disabled:opacity-50"
                        >
                          <Ban className="w-3.5 h-3.5" />
                          Cancel PO
                        </button>
                      )}
                    </>
                  )}
                  <button
                    onClick={() => handleDownloadPo(selectedPo)}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-200 font-bold rounded-lg shadow-sm cursor-pointer transition-colors"
                  >
                    <FileDown className="w-3.5 h-3.5" />
                    Download Details
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
